name: Say bye
description: "Prints goodbye to a person"

inputs:
  name:
    description: "The name of the person"
    required: true

runs:
 using: "composite"
 steps:
  - run: echo "Good Bye, ${{ inputs.name }}"
    shell: bash